export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as HomeScreen } from './HomeScreen'
export { default as ManageExpenses } from './ManageExpenses'
export { default as ManageLeaves } from './ManageLeaves'
export { default as ClaimExpenses } from './ClaimExpenses'
export { default as ApplyLeaves } from './ApplyLeaves'
export { default as ApprovedLeaves } from './ApprovedLeaves'
export { default as Task } from './Task'
export { default as VisitSummaryReport } from './VisitSummaryReport'
export { default as VSRForm} from './VSRFrom'
export { default as DoctorDetails } from './DoctorDetails'
export { default as ProductDetails } from './ProductDetails'
   